fix(integration_tests): Exit on keyspace initialization failure in CDC server setup
- The script previously continued execution even if the `curl` command to initialize the keyspace failed.
- This could lead to silent setup failures and subsequent cryptic test errors.
- Added error handling to exit the script if keyspace initialization fails, providing clearer debugging information.

Signed-off-by: tenfyzhong <tenfy@tenfy.cn>

diff --git a/tests/integration_tests/_utils/run_cdc_server b/tests/integration_tests/_utils/run_cdc_server
--- a/tests/integration_tests/_utils/run_cdc_server
+++ b/tests/integration_tests/_utils/run_cdc_server
@@ -200,7 +200,10 @@ done
 
 # for the next gen, we should create they keyspace info to replication worker
 if [ "$IS_NEXT_GEN" = "1" ]; then
-	curl -X POST "http://$TIKV_WORKER_HOST:$TIKV_WORKER_PORT/cdc/keyspace?keyspace_id=1" -H 'Content-Type: Application/json' -d "{\"pd_url\": \"http://${UP_PD_HOST_1}:${CDC_PD_PORT}\", \"cdc_addr\": \"$addr_url\"}"
+	if ! curl -X POST "http://$TIKV_WORKER_HOST:$TIKV_WORKER_PORT/cdc/keyspace?keyspace_id=1" -H 'Content-Type: Application/json' -d "{\"pd_url\": \"http://${UP_PD_HOST_1}:${CDC_PD_PORT}\", \"cdc_addr\": \"$addr_url\"}"; then
+		echo "init keyspace failed" >&2
+		exit 1
+	fi
 fi
 
 set +x
